"""Markdown report generator for a :class:`VerificationPlan`.

Renders a reviewable draft: header + non-claims, approval summary, risk-ranked
plan items, feature list, proposed scenarios, assertion candidates, coverage
targets, requirement ambiguities, and the traceability matrix. Output is
deterministic so it can be golden-tested.
"""

from __future__ import annotations

from .models import ApprovalState, VerificationPlan

_NON_CLAIMS = [
    "This is a **proposed draft**, not an approved verification plan. Every item "
    "is `proposed` until a human records an approval decision.",
    "Assertion candidates are **sketches** (may not compile, may be incomplete or "
    "wrong). They are heuristic templates, not proven properties.",
    "Classification, techniques and risk scores are **deterministic heuristics**, "
    "not a formal completeness or coverage guarantee.",
    "No RTL, spec, assumptions, proof scope or signoff conclusion is modified by "
    "this tool.",
]


def _badge(state: ApprovalState) -> str:
    return {
        ApprovalState.PROPOSED: "🟡 proposed",
        ApprovalState.APPROVED: "🟢 approved",
        ApprovalState.REJECTED: "🔴 rejected",
    }[state]


def _join(ids: list[str]) -> str:
    return ", ".join(ids) if ids else "—"


def render_markdown(plan: VerificationPlan) -> str:
    lines: list[str] = []
    p = plan.provenance

    lines.append(f"# Verification Plan Draft — {plan.design_name}")
    lines.append("")
    lines.append(
        f"_Generated by `{p.tool}` v{p.tool_version} "
        f"(schema {plan.schema_version}, LLM adapter: {p.llm_adapter})._"
    )
    lines.append("")

    # Non-claims -----------------------------------------------------------
    lines.append("## Non-claims / status")
    for nc in _NON_CLAIMS:
        lines.append(f"- {nc}")
    lines.append("")

    # Approval summary -----------------------------------------------------
    counts = plan.counts_by_approval()
    lines.append("## Approval summary")
    lines.append("")
    lines.append("| State | Count |")
    lines.append("| --- | --- |")
    for state in ApprovalState:
        lines.append(f"| {_badge(state)} | {counts[state.value]} |")
    lines.append("")

    # Risk-ranked plan items ----------------------------------------------
    lines.append("## Risk-ranked verification-plan items")
    lines.append("")
    lines.append("| Plan | Feature | Category | Priority | Risk | Techniques | Status |")
    lines.append("| --- | --- | --- | --- | ---: | --- | --- |")
    for item in plan.plan_items:
        techs = ", ".join(t.value for t in item.techniques)
        lines.append(
            f"| {item.id} | {item.feature_id} | {item.category.value} | "
            f"{item.priority.value} | {item.risk_score} | {techs} | "
            f"{_badge(item.approval)} |"
        )
    lines.append("")

    # Feature list ---------------------------------------------------------
    lines.append("## Features")
    lines.append("")
    for f in plan.features:
        lines.append(
            f"- **{f.id}** ({f.category.value}) [{_badge(f.approval)}] — {f.name}  "
        )
        lines.append(
            f"  from {_join(f.source_requirements)}: {f.description}"
        )
    lines.append("")

    # Scenarios ------------------------------------------------------------
    lines.append("## Proposed test scenarios")
    lines.append("")
    lines.append("| Scenario | Feature | Technique | Description | Status |")
    lines.append("| --- | --- | --- | --- | --- |")
    for s in plan.scenarios:
        lines.append(
            f"| {s.id} | {s.feature_id} | {s.technique.value} | {s.description} | "
            f"{_badge(s.approval)} |"
        )
    lines.append("")

    # Assertion candidates -------------------------------------------------
    lines.append("## Proposed assertion candidates (sketches)")
    lines.append("")
    for a in plan.assertions:
        lines.append(f"### {a.id} — {a.feature_id} [{_badge(a.approval)}]")
        lines.append("")
        lines.append("```systemverilog")
        lines.append(a.sva_sketch)
        lines.append("```")
        lines.append(f"_Rationale:_ {a.rationale}")
        lines.append("")

    # Coverage targets -----------------------------------------------------
    lines.append("## Coverage targets")
    lines.append("")
    lines.append("| Coverage | Feature | Metric | Description | Status |")
    lines.append("| --- | --- | --- | --- | --- |")
    for c in plan.coverage_targets:
        lines.append(
            f"| {c.id} | {c.feature_id} | {c.metric} | {c.description} | "
            f"{_badge(c.approval)} |"
        )
    lines.append("")

    # Ambiguities ----------------------------------------------------------
    lines.append("## Requirement ambiguities / missing requirements / assumptions")
    lines.append("")
    if plan.ambiguities:
        lines.append("| ID | Kind | Ref | Detail |")
        lines.append("| --- | --- | --- | --- |")
        for amb in plan.ambiguities:
            lines.append(
                f"| {amb.id} | {amb.kind.value} | {amb.ref or '—'} | {amb.detail} |"
            )
    else:
        lines.append("_None detected._")
    lines.append("")

    # Traceability ---------------------------------------------------------
    lines.append("## Traceability matrix (requirement → tests → coverage)")
    lines.append("")
    lines.append(
        "| Requirement | Features | Scenarios | Assertions | Coverage | "
        "Existing | Covered |"
    )
    lines.append("| --- | --- | --- | --- | --- | --- | --- |")
    for row in plan.traceability:
        covered = "✅" if row.covered else "❌"
        lines.append(
            f"| {row.requirement_id} | {_join(row.feature_ids)} | "
            f"{_join(row.scenario_ids)} | {_join(row.assertion_ids)} | "
            f"{_join(row.coverage_ids)} | {_join(row.existing_testplan_ids)} | "
            f"{covered} |"
        )
    lines.append("")

    uncovered = [r.requirement_id for r in plan.traceability if not r.covered]
    if uncovered:
        lines.append(
            f"> ⚠️ **{len(uncovered)} requirement(s) not yet covered:** "
            f"{_join(uncovered)}"
        )
        lines.append("")

    return "\n".join(lines)
